### ISSUE TITLE
Improve in-app documentation

### ISSUE THREAD

**Issue by mbannert** [iscience-kn/dropR#4]
- [x] Refer to pkgdown page on github.io
- [x] Better wording inside the app

What else  did you find @the-tave ?

**Comment by the-tave** [comment]
- [ ] Home Tab: Format text (less wide) & state more clearly what dropR can do
- [ ] Upload Tab: add very short description of the type of data in the demo data & maybe add a custom option for "Interpret as missing"?
- [ ] Visual Inspection Tab: add caption with N & dropout rates + add possibility to change axis labels (or just make them clearer, "dropout index" seems ambiguous and not to reflect what it actually shows, which is question number, right?) + check svg export because it did not work when I tried it

**Comment by the-tave** [comment]
- [x] Home Tab: Format text (less wide) & state more clearly what dropR can do
- [x] Upload Tab: add very short description of the type of data in the demo data & maybe add a custom option for "Interpret as missing"?
 - [x] Visual Inspection Tab: add caption with N & dropout rates + add possibility to change axis labels (or just make them clearer, "dropout index" seems ambiguous and not to reflect what it actually shows, which is question number, right?) + check svg export because it did not work when I tried it

(Sorry for the close & reopen, I haven't collaborated on GitHub before so I need to try some functions still :D)

**Comment by mbannert** [comment]
Can you @the-tave  `git checkout -b documentation` (starting from main) and come up with suggestions to improve the text. The text you refer to should be mainly in `inst/app/` in the `ui.R` and the `server.R` file.

**Comment by the-tave** [comment]
@mbannert I worked through the tasks we found and I think the documentation is much clearer now - see Pull request for branch "documentation" :)

**Comment by mbannert** [comment]
I'll take a look at your branch. Please online close issues once PRs are merged into main.
