### ISSUE TITLE
Error: could not find function "extract_drop_out_from_df"

### ISSUE THREAD

**Issue by the-tave** [iscience-kn/dropR#8]
@mbannert , is it possible you accidentally deleted this function? Or renamed it? I can't find it in the R folder where it should be

**Comment by mbannert** [comment]
I've worked quite a bit on the function naming to make it consistent and also changed returns of function to make it more consistent. Something may have gone wrong, but it should only be a minor issue... since I checked the app and documentation examples regularly (also docs are auto-generated and hence run the function when rendering). 

I'll take a look later on.

**Comment by mbannert** [comment]
fixed, re-open with reprex when needed.
